"""add database constraints and relationships

Revision ID: 859e4a062ffa
Revises: 197130132eb0
Create Date: 2026-10-09 11:53:38.078218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '859e4a062ffa'
down_revision: Union[str, Sequence[str], None] = '197130132eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.drop_constraint(op.f('documents_owner_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key('fk_documents_owner_id_users', 'documents', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_check_constraint(
        'ck_documents_filename_not_blank',
        'documents',
        'length(trim(filename)) > 0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_documents_filename_not_blank', 'documents', type_='check')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('fk_documents_owner_id_users', 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_owner_id_fkey'), 'documents', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
